[features]
seeds = true
skip-lint = false
[programs.localnet]
staking_app = "EisUaNgBLuBWxFRRDH5scNoXBrpp5rbTcomm6bcRBzNB"
lootbox_app = "wPZy7zBjiXQ8w7Q2hQDXzQamv434Q3Xouzjpu5WCPZC"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/nero/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
